name: notifications_shims
description: Notifications shims for Clean-B architecture - Push notifications, local
  notifications
version: 1.0.0
homepage: https://github.com/delivery-ways/delivery-ways
publish_to: none
environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies:
  flutter:
    sdk: flutter
  foundation_shims:
    path: ../../foundation_shims
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
flutter:
  uses-material-design: false
