name: delivery_ways_clean
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: 0.20.2
  meta: 1.16.0
  flutter_riverpod: ^2.6.1
  in_app_review: ^2.0.9
  core: ^0.1.0
  design_system_components: ^1.0.0
  design_system_foundation: ^1.0.0
  payments: ^1.0.0
  foundation_shims: ^0.1.0
  network_shims: ^0.1.0
  maps_shims: ^0.1.0
  mobility_shims: ^0.1.0
  mobility_adapter_geolocator: ^0.1.0
  mobility_stub_impl: ^0.1.0
  pricing_shims: ^0.1.0
  pricing_stub_impl: ^0.1.0
  realtime_shims: ^0.1.0
  design_system_shims: ^1.0.0
  observability_shims: ^0.1.0
  auth_supabase_impl: ^0.1.0
  auth_shims: ^1.0.0
  auth_http_impl: ^1.0.0
  device_security_shims: ^0.1.0
  payments_shims: ^0.1.0
  accounts_shims: ^0.1.0
  b_ui: ^1.0.0
  b_ux: ^1.0.0
  dsr_ux_adapter: ^1.0.0
  accounts_stub_impl: ^0.1.0
  design_system_stub_impl: ^1.0.0
  maps_adapter_google: ^0.1.0
  maps_stub_impl: ^0.1.0
  mobility_uplink_impl: ^0.1.0
  rbac_rest_impl: ^0.1.0
  payments_adapter_stripe: ^1.0.0
  notifications_shims: ^1.0.0
  privacy: ^0.1.0
  parcels_shims: ^0.0.1
  food_shims: ^0.0.1
  http: any
  shared_preferences: any
  geolocator: ^11.1.0
dependency_overrides:
  riverpod: 2.6.1
  flutter_riverpod: 2.6.1
dev_dependencies:
  melos: ^5.3.0
  dart_code_metrics:
    path: third_party/dart_code_metrics
  flutter_test:
    sdk: flutter
  test: any
  integration_test:
    sdk: flutter
  crypto: ^3.0.3
  sqflite: ^2.3.0
  path: ^1.9.0
  uuid: ^4.5.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.11
  path_provider_platform_interface: any
  plugin_platform_interface: any
flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/certs/
  - assets/rbac/
  - assets/legal/
  - lib/l10n/
