name: parcels_shims
description: Domain models and shims for Parcels vertical in Delivery Ways.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  test: ^1.24.0
  lints: any

