name: food_shims
description: "Domain models and ports for Food vertical (restaurants, menu, orders)."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: any

dev_dependencies:
  test: any
  lints: any

