name: mobility_adapter_geofence
description: Geofence adapter for mobility_shims
version: 0.1.0
publish_to: none
environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_background_geolocation: ^4.15.0
  mobility_shims: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: null
