name: foundation_shims
description: Foundation shims for Delivery Ways clean version
publish_to: none
version: 0.1.0
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  http: ^1.2.1
  flutter_riverpod: ^2.6.1
  package_info_plus: ^8.0.0
  network_shims: ^0.1.0
