name: payments_adapter_stripe
description: Stripe adapter implementation for payments package contracts
version: 1.0.0
publish_to: none
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  payments:
    path: ../payments
  foundation_shims:
    path: ../foundation_shims
  payments_stripe_impl:
    path: ../payments_stripe_impl
  flutter_riverpod: any
  payments_shims:
    path: ../payments_shims
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
flutter: null
