name: dsr_ux_adapter
description: UX Compatibility Layer for DSR Components
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: '^3.9.2'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  design_system_foundation: ^1.0.0
  design_system_shims: ^1.0.0
  foundation_shims: ^0.1.0
  flutter_riverpod: ^2.4.9
  design_system_components: ^1.0.0
dev_dependencies:
  flutter_test: any
