name: b_ui
description: B-UI Phase 02
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  flutter_riverpod: ^2.4.9
  design_system_shims: ^1.0.0
  design_system_foundation: ^1.0.0
  design_system_components: ^1.0.0
  foundation_shims: ^0.1.0
  accounts_shims: ^0.1.0
  notifications_shims: ^1.0.0
  auth_shims: ^1.0.0
  auth_http_impl: ^1.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
