name: maps_shims
publish_to: none
version: 0.1.0
environment:
  sdk: '^3.9.2'
dependencies:
  flutter:
    sdk: flutter
  meta: any
  flutter_riverpod: any
dev_dependencies:
  lints: any
  flutter_test:
    sdk: flutter
